"""atualizando

Revision ID: 026e14b375d8
Revises: e60f8dcb55e3
Create Date: 2023-06-13 14:09:19.487016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026e14b375d8'
down_revision = 'e60f8dcb55e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_modopreparo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tb_modoPreparo')
    with op.batch_alter_table('tb_preparacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modoPreparo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tb_modopreparo', ['modoPreparo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_preparacao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('modoPreparo_id')

    op.create_table('tb_modoPreparo',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"tb_modoPreparo_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tb_modoPreparo_pkey')
    )
    op.drop_table('tb_modopreparo')
    # ### end Alembic commands ###
