"""Teste Rhavy

Revision ID: 0383da6b5b89
Revises: 0b175d215907
Create Date: 2023-05-30 16:58:21.038692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0383da6b5b89'
down_revision = '0b175d215907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proprietario_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tb_proprietario', ['proprietario_id'], ['usuario_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_empresa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proprietario_id')

    # ### end Alembic commands ###
