"""Upgrade Test

Revision ID: 0b175d215907
Revises: 5c27f74b9f65
Create Date: 2023-05-30 16:33:22.610520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b175d215907'
down_revision = '5c27f74b9f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_empresa', schema=None) as batch_op:
        batch_op.drop_constraint('tb_empresa_proprietario_id_fkey', type_='foreignkey')
        batch_op.drop_column('proprietario_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proprietario_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tb_empresa_proprietario_id_fkey', 'tb_proprietario', ['proprietario_id'], ['usuario_id'])

    # ### end Alembic commands ###
