"""Fix

Revision ID: 15bb6c4d8d5b
Revises: 1c677a91cdc1
Create Date: 2023-05-30 15:27:59.761496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15bb6c4d8d5b'
down_revision = '1c677a91cdc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_empresa', schema=None) as batch_op:
        batch_op.drop_constraint('tb_empresa_id_proprietario_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_proprietario', ['id_proprietario'], ['usuario_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_empresa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_empresa_id_proprietario_fkey', 'tb_gestor', ['id_proprietario'], ['usuario_id'])

    # ### end Alembic commands ###
