"""Initialized

Revision ID: 1c677a91cdc1
Revises: 
Create Date: 2023-05-30 15:24:20.653644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c677a91cdc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preparacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('componente', sa.String(), nullable=False),
    sa.Column('medidaPorcao', sa.String(), nullable=False),
    sa.Column('tempoPreparo', sa.Integer(), nullable=False),
    sa.Column('rendimento', sa.Float(), nullable=False),
    sa.Column('numPorcao', sa.Float(), nullable=False),
    sa.Column('pesoPorcao', sa.Float(), nullable=False),
    sa.Column('ic', sa.Float(), nullable=False),
    sa.Column('fcg', sa.Float(), nullable=False),
    sa.Column('custoPreparo', sa.Float(), nullable=False),
    sa.Column('custoPorcao', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_cardapio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_ingrediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('pesoBruto', sa.Float(), nullable=False),
    sa.Column('unidade', sa.String(), nullable=False),
    sa.Column('indicadorParteComestivel', sa.Float(), nullable=False),
    sa.Column('pesoLiquido', sa.Float(), nullable=False),
    sa.Column('perCapita', sa.Float(), nullable=False),
    sa.Column('embalagem', sa.Float(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('custPreparacao', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tb_gestor',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('tb_preparador',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('tb_proprietario',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('tb_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('id_proprietario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_proprietario'], ['tb_gestor.usuario_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_empresa')
    op.drop_table('tb_proprietario')
    op.drop_table('tb_preparador')
    op.drop_table('tb_gestor')
    op.drop_table('tb_usuario')
    op.drop_table('tb_ingrediente')
    op.drop_table('tb_cardapio')
    op.drop_table('preparacao')
    # ### end Alembic commands ###
