"""empty message

Revision ID: 253c85e08d9e
Revises: ff8c63991128
Create Date: 2023-06-14 11:12:58.373191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253c85e08d9e'
down_revision = 'ff8c63991128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_modopreparo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_modopreparo', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
