"""Campo Auto-Increment

Revision ID: 31f6d98111f1
Revises: 5274d8d97b65
Create Date: 2023-06-09 15:58:56.609609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f6d98111f1'
down_revision = '5274d8d97b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_utensilio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_utensilio')
    # ### end Alembic commands ###
