"""empty message

Revision ID: 5b913f67858e
Revises: 
Create Date: 2023-06-21 14:21:42.004991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b913f67858e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('exp', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_ingrediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_medidacaseira',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao')
    )
    op.create_table('tb_unidademedida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('tb_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tb_utensilio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_proprietario',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('tb_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('proprietario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proprietario_id'], ['tb_proprietario.usuario_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('tb_cardapio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['tb_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_gestor',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['tb_empresa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('tb_preparacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('criacao', sa.DateTime(), nullable=True),
    sa.Column('numPorcoes', sa.Float(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['tb_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_preparador',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['tb_empresa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('tb_cardapiopreparacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardapio_id', sa.Integer(), nullable=True),
    sa.Column('preparacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cardapio_id'], ['tb_cardapio.id'], ),
    sa.ForeignKeyConstraint(['preparacao_id'], ['tb_preparacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_modopreparo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('criacao', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('preparacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['preparacao_id'], ['tb_preparacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_preparacao_ingrediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preparacao_id', sa.Integer(), nullable=True),
    sa.Column('ingrediente_id', sa.Integer(), nullable=True),
    sa.Column('pesoBruto', sa.Float(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('indicadorParteComestivel', sa.Float(), nullable=False),
    sa.Column('pesoLiquido', sa.Float(), nullable=False),
    sa.Column('perCapita', sa.Float(), nullable=False),
    sa.Column('medidaCaseira_id', sa.Integer(), nullable=True),
    sa.Column('embalagem', sa.Float(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('custoPreparacao', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['tb_ingrediente.id'], ),
    sa.ForeignKeyConstraint(['medidaCaseira_id'], ['tb_medidacaseira.id'], ),
    sa.ForeignKeyConstraint(['preparacao_id'], ['tb_preparacao.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['tb_unidademedida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_utensiliopreparacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utensilio_id', sa.Integer(), nullable=True),
    sa.Column('preparacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['preparacao_id'], ['tb_preparacao.id'], ),
    sa.ForeignKeyConstraint(['utensilio_id'], ['tb_utensilio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_utensiliopreparacao')
    op.drop_table('tb_preparacao_ingrediente')
    op.drop_table('tb_modopreparo')
    op.drop_table('tb_cardapiopreparacao')
    op.drop_table('tb_preparador')
    op.drop_table('tb_preparacao')
    op.drop_table('tb_gestor')
    op.drop_table('tb_cardapio')
    op.drop_table('tb_empresa')
    op.drop_table('tb_proprietario')
    op.drop_table('tb_utensilio')
    op.drop_table('tb_usuario')
    op.drop_table('tb_unidademedida')
    op.drop_table('tb_medidacaseira')
    op.drop_table('tb_ingrediente')
    op.drop_table('tb_blacklist')
    # ### end Alembic commands ###
