"""test

Revision ID: 70d65421b0b4
Revises: 15bb6c4d8d5b
Create Date: 2023-05-30 15:43:41.100075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d65421b0b4'
down_revision = '15bb6c4d8d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proprietario', sa.Integer(), nullable=True))
        batch_op.drop_constraint('tb_empresa_id_proprietario_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_proprietario', ['proprietario'], ['usuario_id'])
        batch_op.drop_column('id_proprietario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_proprietario', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_empresa_id_proprietario_fkey', 'tb_proprietario', ['id_proprietario'], ['usuario_id'])
        batch_op.drop_column('proprietario')

    # ### end Alembic commands ###
