"""empty message

Revision ID: 75a1f51a7934
Revises: 026e14b375d8
Create Date: 2023-06-13 16:47:55.201374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a1f51a7934'
down_revision = '026e14b375d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_modopreparo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('preparacao_id', sa.Integer(), nullable=True))
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'tb_preparacao', ['preparacao_id'], ['id'])

    with op.batch_alter_table('tb_preparacao', schema=None) as batch_op:
        batch_op.drop_constraint('tb_preparacao_modoPreparo_id_fkey', type_='foreignkey')
        batch_op.drop_column('modoPreparo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_preparacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modoPreparo_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tb_preparacao_modoPreparo_id_fkey', 'tb_modopreparo', ['modoPreparo_id'], ['id'])

    with op.batch_alter_table('tb_modopreparo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('preparacao_id')
        batch_op.drop_column('criacao')

    # ### end Alembic commands ###
