"""empty message

Revision ID: 7b15ec6c49cd
Revises: 8fa324e0ad8c
Create Date: 2023-06-11 16:00:28.060636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b15ec6c49cd'
down_revision = '8fa324e0ad8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('exp', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tb_blackList')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_blackList',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"tb_blackList_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('exp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tb_blackList_pkey')
    )
    op.drop_table('tb_blacklist')
    # ### end Alembic commands ###
