"""empty message

Revision ID: 8fa324e0ad8c
Revises: 92c528a093c3
Create Date: 2023-06-11 15:54:19.863147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fa324e0ad8c'
down_revision = '92c528a093c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_blackList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('exp', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tb_BlackList')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_BlackList',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"tb_BlackList_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('exp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tb_BlackList_pkey')
    )
    op.drop_table('tb_blackList')
    # ### end Alembic commands ###
