"""empty message

Revision ID: 9bad05b85f1f
Revises: b101c9e44f40
Create Date: 2023-07-01 18:37:32.774157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bad05b85f1f'
down_revision = 'b101c9e44f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_ingrediente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_ingrediente', schema=None) as batch_op:
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###
