"""empty message

Revision ID: b101c9e44f40
Revises: fa1aaff382d8
Create Date: 2023-06-30 17:49:03.671931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b101c9e44f40'
down_revision = 'fa1aaff382d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_imgpreparacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fotoPerfil', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_imgpreparacao', schema=None) as batch_op:
        batch_op.drop_column('fotoPerfil')

    # ### end Alembic commands ###
