"""empty message

Revision ID: d6fb16858140
Revises: 88cb01573022
Create Date: 2023-06-30 17:32:01.817960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6fb16858140'
down_revision = '88cb01573022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_imgpreparacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preparacao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tb_imgpreparacao', ['preparacao_id'], ['id'])
        batch_op.drop_column('fotoPerfil')

    with op.batch_alter_table('tb_preparacao', schema=None) as batch_op:
        batch_op.drop_constraint('tb_preparacao_fotoPerfil_id_fkey', type_='foreignkey')
        batch_op.drop_column('fotoPerfil_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_preparacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fotoPerfil_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tb_preparacao_fotoPerfil_id_fkey', 'tb_imgpreparacao', ['fotoPerfil_id'], ['id'])

    with op.batch_alter_table('tb_imgpreparacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fotoPerfil', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('preparacao_id')

    # ### end Alembic commands ###
