"""Update

Revision ID: eebf72929a20
Revises: 31f6d98111f1
Create Date: 2023-06-09 16:25:18.737948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebf72929a20'
down_revision = '31f6d98111f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_utensilio', schema=None) as batch_op:
        batch_op.drop_column('posicao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_utensilio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posicao', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
