"""empty message

Revision ID: f115d1669e33
Revises: 
Create Date: 2023-06-26 22:29:47.705732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f115d1669e33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_imagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagem', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_preparacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tb_imagem', ['imagem_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_preparacao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('imagem_id')

    op.drop_table('tb_imagem')
    # ### end Alembic commands ###
