"""empty message

Revision ID: fa1aaff382d8
Revises: d6fb16858140
Create Date: 2023-06-30 17:34:14.243195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1aaff382d8'
down_revision = 'd6fb16858140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_imgpreparacao', schema=None) as batch_op:
        batch_op.drop_constraint('tb_imgpreparacao_preparacao_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_preparacao', ['preparacao_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_imgpreparacao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_imgpreparacao_preparacao_id_fkey', 'tb_imgpreparacao', ['preparacao_id'], ['id'])

    # ### end Alembic commands ###
