"""Retirada do delete logico pelo fisico

Revision ID: fe8e5c1e3206
Revises: 5b913f67858e
Create Date: 2023-06-28 14:53:16.856739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8e5c1e3206'
down_revision = '5b913f67858e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_modopreparo', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_modopreparo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
